#!/bin/bash

echo "════════════════════════════════════════════════════════"
echo "🔍 VERIFICAR PROGRESO DEL BUILD"
echo "════════════════════════════════════════════════════════"
echo ""
echo "1️⃣ Ve a Cloud Build:"
echo "   https://console.cloud.google.com/cloud-build/builds?project=master-might-274420"
echo ""
echo "2️⃣ Busca el build más reciente (debería estar RUNNING)"
echo ""
echo "3️⃣ Haz click en el build ID para ver los logs EN TIEMPO REAL"
echo ""
echo "════════════════════════════════════════════════════════"
echo "🎯 QUÉ BUSCAR EN LOS LOGS:"
echo "════════════════════════════════════════════════════════"
echo ""
echo "✅ CORRECTO (build funcionando):"
echo "   - 'Downloading from central: https://repo.maven.apache.org/...'"
echo "   - 'Downloaded: ... (XXX kB at YYY kB/s)'"
echo "   - '[INFO] Compiling XX source files to ...'"
echo "   - '[INFO] Building jar: .../target/falta-uno-0.0.1-SNAPSHOT.jar'"
echo "   - 'BUILD SUCCESS'"
echo "   - Tiempo total: 3-5 minutos"
echo ""
echo "❌ INCORRECTO (usando cache o fallando):"
echo "   - Termina en menos de 1 minuto"
echo "   - NO muestra 'Downloading from central'"
echo "   - NO muestra 'Compiling XX source files'"
echo "   - Usa 'CACHED' layers"
echo ""
echo "════════════════════════════════════════════════════════"
echo "⏱️ TIEMPO ESPERADO:"
echo "════════════════════════════════════════════════════════"
echo ""
echo "Step 1 (Docker build): 5-8 minutos"
echo "  └─ Maven download dependencies: 2-3 min"
echo "  └─ Maven compile: 1-2 min"
echo "  └─ Create JAR: 30 seg"
echo "  └─ Copy to runtime image: 10 seg"
echo ""
echo "Step 2 (Docker push): 30-60 segundos"
echo ""
echo "Step 3 (Deploy to Cloud Run): 1-2 minutos"
echo ""
echo "TOTAL: ~8-12 minutos"
echo ""
echo "════════════════════════════════════════════════════════"
echo ""
echo "Si termina en menos de 2 minutos → ALGO ESTÁ MAL"
echo "Debería estar descargando dependencies y compilando código"
echo ""
