#!/bin/bash

echo "🔍 Para ver los logs de Cloud Build:"
echo ""
echo "1. Abrí este link:"
echo "   https://console.cloud.google.com/cloud-build/builds?project=master-might-274420"
echo ""
echo "2. Click en el build MÁS RECIENTE (el primero de la lista)"
echo ""
echo "3. Buscá en los logs:"
echo "   - 'BUILD FAILURE' o 'BUILD SUCCESS'"
echo "   - 'JAR file:' (el output que agregué)"
echo "   - Cualquier error de Maven"
echo ""
echo "4. Si ves 'BUILD SUCCESS', copiá la sección donde dice 'JAR file:'"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "IMPORTANTE: Si el build falla AHÍ, el problema es de Maven/Java"
echo "           Si el build SUCCESS pero Cloud Run falla, es otro tema"
