#!/bin/bash
set -e

echo "🔍 Verificando estado de Cloud Run..."
echo ""
echo "📋 Instrucciones:"
echo "1. Abrí este link en tu navegador:"
echo "   https://console.cloud.google.com/run/detail/us-central1/faltauno-backend?project=master-might-274420"
echo ""
echo "2. Fijate en la sección 'REVISIONS'"
echo ""
echo "3. La revisión activa debería mostrar:"
echo "   - Estado: ✓ (verde)"
echo "   - Traffic: 100%"
echo "   - Container image tag (fijate si tiene el SHA del commit 2852a4d)"
echo ""
echo "4. Si hay una revisión nueva con 0% traffic, significa que:"
echo "   - El build terminó"
echo "   - La nueva versión falló el health check"
echo "   - No se le asignó tráfico"
echo ""
echo "5. Hacé click en la revisión más nueva para ver sus logs"
echo ""
echo "═══════════════════════════════════════════════"
echo "GitHub Actions build status:"
echo "https://github.com/joacob484/Backend_SD/actions"
echo ""
echo "Último commit que debería estar desplegado:"
echo "2852a4d - fix: arreglar conflicto de versiones Cloud SQL"
echo "═══════════════════════════════════════════════"
