steps:
  # Build the Docker image and tag it with the short commit sha
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/faltauno-backend:$BUILD_ID', '-f', 'Dockerfile.cloudrun', '.' ]

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/faltauno-backend:$BUILD_ID' ]

  # Deploy to Cloud Run using the pushed image. Use substitutions for secrets/envs.
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - 'scripts/cloudrun-deploy.sh'
      - '${_SPRING_DATASOURCE_PASSWORD}'
      - '${_REDIS_HOST}'
      - '${_POSTGRES_HOST}'
      - '${_CLOUDSQL_INSTANCE}'
      - '${_SPRING_DATASOURCE_URL}'
      - '${_SPRING_DATASOURCE_USERNAME}'
      - '$BUILD_ID'

images:
  - 'gcr.io/$PROJECT_ID/faltauno-backend:$BUILD_ID'

substitutions:
  _SPRING_DATASOURCE_PASSWORD: "REPLACE_AT_SUBMIT"
  _REDIS_HOST: "REPLACE_AT_SUBMIT"
  _POSTGRES_HOST: "REPLACE_AT_SUBMIT"
  _CLOUDSQL_INSTANCE: ""
  _SPRING_DATASOURCE_USERNAME: "app"
  # Leave SPRING URL empty so the deploy script synthesizes a safe, connector-aware URL.
  _SPRING_DATASOURCE_URL: ""
