steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -euo pipefail
        SERVICE="faltauno-backend-test"
        REGION="us-central1"
        PROJECT_ID="${PROJECT_ID}"
        IMAGE="$IMAGE"
        # Deploy no-traffic revision
        gcloud run deploy "$SERVICE" \
          --image "$IMAGE" \
          --region "$REGION" \
          --project "$PROJECT_ID" \
          --no-traffic \
          --set-env-vars "SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL},SPRING_REDIS_HOST=${SPRING_REDIS_HOST},SPRING_REDIS_PORT=${SPRING_REDIS_PORT},"

        # get service url
        URL=$(gcloud run services describe "$SERVICE" --region "$REGION" --project "$PROJECT_ID" --format="value(status.url)")
        echo "Service URL=$URL"

        # run smoke test
        /workspace/ci/smoke-actuator.sh "$URL" 60

        echo "Smoke passed. Promotion can proceed."
        # Optionally promote to 100%:
        if [ "${PROMOTE:-false}" = "true" ]; then
          gcloud run services update-traffic "$SERVICE" --to-latest --project "$PROJECT_ID" --region "$REGION"
        fi
substitutions:
  _PLACEHOLDER: ""
timeout: 1200s
steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['-B','-DskipTests','package']
  dir: '.'

# Optional: build and push image for integration tests
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','us-central1-docker.pkg.dev/$PROJECT_ID/faltauno/faltauno-backend:ci-$SHORT_SHA','-f','Dockerfile.cloudrun','.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','us-central1-docker.pkg.dev/$PROJECT_ID/faltauno/faltauno-backend:ci-$SHORT_SHA']

# Optionally deploy no-traffic and run smoke test (requires permissions)
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     gcloud run deploy faltauno-backend-test --image=us-central1-docker.pkg.dev/$PROJECT_ID/faltauno/faltauno-backend:ci-$SHORT_SHA --no-traffic --region=us-central1 --project=$PROJECT_ID
#     gcloud run services list --platform=managed --project=$PROJECT_ID --region=us-central1

options:
  substitutionOption: 'ALLOW_LOOSE'
substitutions:
  _SOME_VAR: "value"
timeout: '1200s'
