steps:
  # Build the Docker image and tag it with the build ID
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/faltauno-backend:$BUILD_ID', '-f', 'Dockerfile.cloudrun', '.' ]

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/faltauno-backend:$BUILD_ID' ]

  # Deploy to Cloud Run using simplified script
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - 'scripts/cloudrun-deploy-simple.sh'
    env:
      - 'BUILD_ID=$BUILD_ID'

images:
  - 'gcr.io/$PROJECT_ID/faltauno-backend:$BUILD_ID'
