#!/bin/bash

echo "🔍 Links de diagnóstico de Cloud Run"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  SERVICIO PRINCIPAL:"
echo "https://console.cloud.google.com/run?project=master-might-274420"
echo ""
echo "2️⃣  LOGS GENERALES (todos los servicios):"
echo "https://console.cloud.google.com/logs?project=master-might-274420"
echo ""
echo "3️⃣  CLOUD BUILD (historial de builds):"
echo "https://console.cloud.google.com/cloud-build/builds?project=master-might-274420"
echo ""
echo "4️⃣  GITHUB ACTIONS (workflows):"
echo "https://github.com/joacob484/Backend_SD/actions"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📋 INSTRUCCIONES:"
echo ""
echo "1. Abrí el link 1️⃣  para ver TODOS los servicios de Cloud Run"
echo "   - ¿Aparece 'faltauno-backend' en la lista?"
echo "   - Si NO aparece, el servicio no existe o no tenés permisos"
echo ""
echo "2. Abrí el link 3️⃣  para ver el último build"
echo "   - ¿El último build dice SUCCESS o FAILED?"
echo "   - Click en el build más reciente para ver detalles"
echo ""
echo "3. Abrí el link 4️⃣  para ver GitHub Actions"
echo "   - ¿El último workflow tiene un ✓ verde o ✗ rojo?"
echo ""
echo "════════════════════════════════════════════════════════════"
