version: '3.8'

networks:
  faltauno-network:
    external: true
    name: backend_sd_faltauno-network

services:
  # Green deployment (nuevo)
  backend-green:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: backend-green
    ports:
      - "8081:8080"  # Mapea al puerto 8081 del host
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - SPRING_REDIS_HOST=faltauno_redis
      - SPRING_REDIS_PORT=6379
      - SPRING_RABBITMQ_HOST=faltauno_rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    networks:
      - faltauno-network
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health/readiness"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

