#!/bin/bash

echo "📋 Últimos logs del backend en Cloud Run..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Abriendo logs en el navegador..."
echo ""
echo "🔗 Cloud Run Service Logs:"
echo "https://console.cloud.google.com/run/detail/us-central1/faltauno-backend/logs?project=master-might-274420"
echo ""
echo "🔗 Cloud Build History:"
echo "https://console.cloud.google.com/cloud-build/builds?project=master-might-274420"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Por favor copia y pega los errores que veas en rojo en los logs."
echo ""
