steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -euo pipefail
    echo "Getting GKE credentials..."
    gcloud container clusters get-credentials faltauno-rabbitmq --region=us-central1 --project=master-might-274420
    echo "Waiting for LoadBalancer IP (up to 5 minutes)..."
    for i in {1..30}; do
      IP=$(kubectl get svc --namespace rabbitmq rabbitmq -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || true)
      if [ -n "$$IP" ]; then
        echo "RABBIT_SERVICE_IP=$$IP"
        exit 0
      fi
      echo "(waiting) attempt $i - no IP yet"
      sleep 10
    done
    echo "ERROR: load balancer IP not found after wait"
    exit 1
